### ISSUE TITLE
Upgrading instead of downgrading 

### ISSUE THREAD

**Issue by MatLCGPro** [The12thAvenger/DS3HavokConverter#1]
Could this tool be able to make the reverse process? To upgrade havok files instead of dowgrading? Amazing work by the way!

**Comment by The12thAvenger** [comment]
Thank you! Unfortunately the tool does not support the opposite conversion at the moment and due to the way it's written it would take some work to make it go the other way. The reason I do not plan to implement that is because the tool only handles things in xml form currently, so it requires Havok Content Tools 2018 for conversion from binary to xml. HCT 2018 comes with a utility called FileConvert which will automatically upgrade old files and apply patches, so writing a different tool to convert things in that direction is pointless unless it can handle binary files and operate independently of HCT.

**Comment by MatLCGPro** [comment]
So HCT 2018 by itself is able to upgrade the files?

**Comment by The12thAvenger** [comment]
For converting from 2014 specifically you'd need to rebuild FileConvert to include hkCompatFormats

**Comment by MatLCGPro** [comment]
I see. And just one more question, it's a bit unrelated to this tool, but it's hard to find people with this knowledge. Using HCT could you create totaly new characters? Would the game be able to use a character with a completely new and unique skeleton and animations exported using HCT?

**Comment by The12thAvenger** [comment]
Yes that is possible. Have you joined the modding discord? It's a better place to get info and help with this stuff.

**Comment by MatLCGPro** [comment]
That's great to hear! Yeah I'm there, but usually people refer to these tools, so I'm just trying to put everything together and cover all my bases. Thank you! I'll keep trying to learn more about these subjects!
